### ISSUE TITLE
LazyLoadQueryResult Exception if result is empty

### ISSUE THREAD

**Issue by dhakehurst** [datanucleus/datanucleus-neo4j#25]
List<? extends Persistable> result = jdoQuery.executeList(); //or jdoQuery.execute();

if this returns a LazyLoadQueryResult, with no items in the result,

calling, result.size(), result.isEmpty(), etc.
results in an Exception, see stacktrace below.

The problem might be in "LazyLoadQueryResult.getNextObject()" which calls 'next' without protecting it with a call to 'hasNext'

java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:71)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:70)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:93)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator.decoratedCypherException(ResultIterator.scala:102)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator.failIfThrows(ResultIterator.scala:91)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator.next(ResultIterator.scala:70)
	at org.neo4j.cypher.internal.compiler.v3_0.ClosingIterator.next(ResultIterator.scala:48)
	at org.neo4j.cypher.internal.compiler.v3_0.PipeExecutionResult.next(PipeExecutionResult.scala:75)
	at org.neo4j.cypher.internal.compiler.v3_0.PipeExecutionResult$$anon$2.next(PipeExecutionResult.scala:68)
	at org.neo4j.cypher.internal.compiler.v3_0.PipeExecutionResult$$anon$2.next(PipeExecutionResult.scala:66)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anon$1$$anonfun$next$1.apply(CompatibilityFor3_0.scala:240)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anon$1$$anonfun$next$1.apply(CompatibilityFor3_0.scala:240)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:117)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anon$1.next(CompatibilityFor3_0.scala:239)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_0$$anon$1.next(CompatibilityFor3_0.scala:233)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.next(ExecutionResult.java:241)
	at org.datanucleus.store.neo4j.query.LazyLoadQueryResult.getNextObject(LazyLoadQueryResult.java:266)
	at org.datanucleus.store.neo4j.query.LazyLoadQueryResult.getSizeUsingMethod(LazyLoadQueryResult.java:209)
	at org.datanucleus.store.query.AbstractQueryResult.size(AbstractQueryResult.java:357)
	at org.datanucleus.store.query.AbstractQueryResult.isEmpty(AbstractQueryResult.java:299)
	at org.datanucleus.store.neo4j.query.LazyLoadQueryResult.getNextObject(LazyLoadQueryResult.java:266)
	at org.datanucleus.store.neo4j.query.LazyLoadQueryResult.getSizeUsingMethod(LazyLoadQueryResult.java:209)
	at org.datanucleus.store.query.AbstractQueryResult.size(AbstractQueryResult.java:357)
	at org.datanucleus.store.query.AbstractQueryResult.isEmpty(AbstractQueryResult.java:299)

**Comment by dhakehurst** [comment]
I have made a local modification of LazyLoadQueryResult.getNextObject() to

    protected Object getNextObject()
    {
        if (result == null)
        {
            // Already exhausted
            return null;
        }

        if (result.hasNext()) {
            Map<String, Object> map = result.next();
            Object rowResult = getResultFromMapRow(map);
            itemsByIndex.put(itemsByIndex.size(), rowResult);
            return rowResult;
        } else {
            // Reached end of results, so null the iterator to signify this
            result.close();
            result = null;
            return null;
        }

    }

which seems to work

**Comment by andyjefferson** [comment]
When I have a query that has no results (org.datanucleus.store.neo4j.query.LazyLoadQueryResult) all works fine, so please create a testcase as per the provided template so we can see what you see. Thx

**Comment by dhakehurst** [comment]
Where are the test cases ? and the template?
expected to find them in src/test/java !

**Comment by andyjefferson** [comment]
The testcase template was on the "New Issue" page when you raised this (and presumably deleted the template text). It contained the URL http://www.datanucleus.org/documentation/problem_reporting.html
which, for JDO, points to
https://github.com/datanucleus/test-jdo

**Comment by dhakehurst** [comment]
Test case

https://github.com/dhakehurst/test-jdo.git

**Comment by dhakehurst** [comment]
Test executed on:

macOS Sierra
Version 10.12.3

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by andyjefferson** [comment]
Your patch applied, thx. 

FWIW you do not supply "ConnectionDriver" to Neo4j since it will be ignored as per the docs. You also do not need to play around with properties to create a PMF, when the test template already has a persistence.xml defined with all of that in.
