### ISSUE TITLE
Multiple Primary Keys fail

### ISSUE THREAD

**Issue by dhakehurst** [datanucleus/datanucleus-neo4j#29]
version: 5.1.0-m1
test: https://github.com/dhakehurst/test-jdo, SimpleTest.MultiplePrimaryKeys()

JDO allows for multiple primary key fields.
The documentation/tutorial for datanucleus-neo4j indicates we can have multiple primary keys.

but when using multiple primary keys, we get an exception (see below).

java.lang.NoSuchMethodError: mydomain.model.MultiKey_PK.setId1(Ljava/lang/Long;)V
	at mydomain.model.MultiKey.dnCopyKeyFieldsToObjectId(MultiKey.java)
	at org.datanucleus.identity.IdentityManagerImpl.getApplicationId(IdentityManagerImpl.java:461)
	at org.datanucleus.ExecutionContextImpl.newObjectId(ExecutionContextImpl.java:3705)
	at org.datanucleus.state.StateManagerImpl.setIdentity(StateManagerImpl.java:2305)
	at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:482)
	at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:122)
	at org.datanucleus.state.ObjectProviderFactoryImpl.newForPersistentNew(ObjectProviderFactoryImpl.java:218)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2013)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1857)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1712)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at org.datanucleus.test.SimpleTest.MultiplePrimaryKeys(SimpleTest.java:201)

**Comment by dhakehurst** [comment]
(There is a test case..second line of comment!)

However, maybe it is my mistake,

could be that I need a 'PrimaryKey class',
(http://www.datanucleus.org/products/accessplatform_3_3/jdo/primary_key.html)

I will check

**Comment by andyjefferson** [comment]
No PK class defined (required by the JDO spec), and the DN helper to auto-generate a PK (PrimaryKeyGenerator) is only applicable for persistable fields (not persistable properties). So either use persistable fields, or provide a PK class, or contribute code to make the PrimaryKeyGenerator support persistable properties
